version: "3.9"

networks:
  web-api-app-dev:
    driver: bridge

services:
  app:
    container_name: web-api-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - postgres_db 
    networks:
      - web-api-app-dev
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres 
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: volgait-dev
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432" 
    networks:
      - web-api-app-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data 

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "vova@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "vova"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - web-api-app-dev
    depends_on:
      - app
        
volumes:
  postgres-data: 
  pgadmin-data:
