version: "3.9"

networks:
  web-api-app-dev:
    driver: bridge

services:
  app:
    container_name: web-api-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - web-api-app-dev
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres 
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: volgait
    ports:
      - "5432:5432" 
    networks:
      - web-api-app-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data 
        
volumes:
  postgres-data: